<?php

return [
    'health_weights' => [
        'trial_onboarding_started' => 5,
        'trial_branch_created' => 5,
        'trial_cashbox_created' => 5,
        'trial_supplier_created' => 5,
        'product_created' => 10,
        'trial_purchase_order_created' => 10,
        'trial_purchase_order_received' => 15,
        'trial_inventory_verified' => 10,
        'trial_customer_created' => 10,
        'trial_reservation_created' => 15,
        'trial_balances_viewed' => 5,
        'trial_statement_viewed' => 5,
    ],

    'health_labels' => [
        'trial_onboarding_started' => 'بدء التجربة',
        'trial_branch_created' => 'إنشاء فرع',
        'trial_cashbox_created' => 'إنشاء خزنة',
        'trial_supplier_created' => 'إضافة مورد',
        'product_created' => 'إضافة منتج',
        'trial_purchase_order_created' => 'إنشاء طلبية',
        'trial_purchase_order_received' => 'استلام طلبية',
        'trial_inventory_verified' => 'استخدام المخزون',
        'trial_customer_created' => 'إضافة عميلة',
        'trial_reservation_created' => 'إنشاء حجز',
        'trial_balances_viewed' => 'مشاهدة الأرصدة',
        'trial_statement_viewed' => 'مشاهدة كشف الحساب',
        'active_today' => 'نشط اليوم',
    ],

    'activity_labels' => [
        'trial_onboarding_started' => 'بدأ رحلة التجربة',
        'trial_branch_created' => 'أنشأ فرعًا',
        'trial_cashbox_created' => 'أنشأ خزنة',
        'trial_supplier_created' => 'أضاف موردًا',
        'trial_purchase_order_created' => 'أنشأ طلبية',
        'trial_purchase_order_received' => 'استلم الطلبية',
        'trial_inventory_verified' => 'تأكد من ظهور المنتجات في المخزون',
        'trial_customer_created' => 'أضاف عميلة',
        'trial_reservation_created' => 'أنشأ حجزًا',
        'trial_balances_viewed' => 'شاهد الأرصدة',
        'trial_statement_viewed' => 'شاهد كشف الحساب',
        'trial_onboarding_completed' => 'أكمل رحلة التجربة',
        'trial_pricing_viewed' => 'اطلع على صفحة الباقات',
        'trial_upgrade_clicked' => 'ضغط على ترقية الباقة',
        'trial_checkout_started' => 'بدأ طلب الترقية',
    ],

    'activity_categories' => [
        'trial_onboarding_started' => 'onboarding',
        'trial_branch_created' => 'onboarding',
        'trial_cashbox_created' => 'onboarding',
        'trial_onboarding_completed' => 'onboarding',
        'trial_customer_created' => 'customers',
        'trial_reservation_created' => 'reservations',
        'trial_inventory_verified' => 'inventory',
        'trial_supplier_created' => 'purchases',
        'trial_purchase_order_created' => 'purchases',
        'trial_purchase_order_received' => 'purchases',
        'trial_balances_viewed' => 'finance',
        'trial_statement_viewed' => 'finance',
        'trial_pricing_viewed' => 'system',
        'trial_upgrade_clicked' => 'system',
        'trial_checkout_started' => 'system',
    ],

    'activation_requirements' => [
        'branch',
        'cashbox',
        'product',
        'purchase_received',
        'customer',
        'reservation',
        'financial_view',
    ],

    'inactive_after_hours' => 48,
    'hot_recent_hours' => 24,
    'activity_per_page' => 30,

    'activity_icons' => [
        'trial_onboarding_started' => 'ri-flag-line',
        'trial_branch_created' => 'ri-building-line',
        'trial_cashbox_created' => 'ri-safe-2-line',
        'trial_supplier_created' => 'ri-store-2-line',
        'trial_purchase_order_created' => 'ri-shopping-cart-line',
        'trial_purchase_order_received' => 'ri-inbox-unarchive-line',
        'trial_inventory_verified' => 'ri-price-tag-3-line',
        'trial_customer_created' => 'ri-user-add-line',
        'trial_reservation_created' => 'ri-calendar-check-line',
        'trial_balances_viewed' => 'ri-bar-chart-2-line',
        'trial_statement_viewed' => 'ri-file-list-3-line',
        'trial_onboarding_completed' => 'ri-checkbox-circle-line',
        'trial_pricing_viewed' => 'ri-money-dollar-circle-line',
        'trial_upgrade_clicked' => 'ri-arrow-up-circle-line',
        'trial_checkout_started' => 'ri-bank-card-line',
    ],
];
